<a href="https://colab.research.google.com/github/decidedlythefirst/-/blob/main/v3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install utils

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting utils
  Downloading utils-1.0.1-py2.py3-none-any.whl (21 kB)
Installing collected packages: utils
Successfully installed utils-1.0.1

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from copy import deepcopy
import utils
import warnings, pylab

warnings.filterwarnings('ignore')

In [ ]:
train = pd.read_csv('/content/train_new.csv')
test = pd.read_csv('/content/test_new.csv')
test

,period_dt,location_id,product_id,demand,PROMO1_FLAG,PROMO2_FLAG,PRICE_REGULAR,PRICE_AFTER_DISC,NUM_CONSULTANT,AUTORIZATION_FLAG,id,STORE_LOCATION_LVL_RK4,STORE_LOCATION_LVL_RK3,PRODUCT_LVL_RK6,id_x
0,2019-12-09,1034.0,103170.0,NaN,1.0,0.0,2849.0,1851.85,0.0,1.0,NaN,203.0,203.0,3874.0,184868.0
1,2019-12-09,1326.0,130598.0,NaN,0.0,0.0,2699.0,1754.35,5.0,1.0,NaN,203.0,203.0,3897.0,201012.0
2,2019-12-09,525.0,103175.0,NaN,0.0,0.0,NaN,NaN,0.0,1.0,NaN,54.0,54.0,3874.0,184919.0
3,2019-12-09,425.0,113725.0,NaN,0.0,0.0,3849.0,2886.75,0.0,1.0,NaN,203.0,203.0,9912.0,194325.0
4,2019-12-09,1191.0,94170.0,NaN,0.0,0.0,4099.0,2049.50,0.0,1.0,NaN,28.0,28.0,9912.0,162351.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
588,2019-12-30,1203.0,130629.0,NaN,1.0,0.0,3949.0,1974.50,0.0,1.0,NaN,26.0,26.0,9912.0,201305.0
589,2019-12-30,1363.0,105604.0,NaN,1.0,0.0,3449.0,1724.50,0.0,1.0,NaN,26.0,26.0,3908.0,190091.0
590,2019-12-30,1034.0,104387.0,NaN,1.0,0.0,4299.0,2149.50,0.0,1.0,NaN,203.0,203.0,9923.0,188922.0
591,2019-12-30,866.0,130630.0,NaN,1.0,0.0,3949.0,1974.50,0.0,1.0,NaN,219.0,219.0,9912.0,201318.0
592,2019-12-30,525.0,148683.0,NaN,0.0,0.0,4899.0,3674.25,0.0,1.0,NaN,54.0,54.0,3881.0,204065.0

In [ ]:
train

,period_dt,location_id,product_id,demand,PROMO1_FLAG,PROMO2_FLAG,PRICE_REGULAR,PRICE_AFTER_DISC,NUM_CONSULTANT,AUTORIZATION_FLAG,id,STORE_LOCATION_LVL_RK4,STORE_LOCATION_LVL_RK3,PRODUCT_LVL_RK6,id_x
0,2016-12-19,540.0,62002.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,70741.0,26.0,26.0,6174.0,NaN
1,2016-12-19,1185.0,62406.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,90373.0,258.0,258.0,3876.0,NaN
2,2016-12-19,798.0,37534.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,49671.0,203.0,203.0,3876.0,NaN
3,2016-12-19,1281.0,62406.0,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,90411.0,203.0,203.0,3876.0,NaN
4,2016-12-19,555.0,32995.0,0.500000,NaN,NaN,NaN,NaN,NaN,NaN,243001.0,258.0,258.0,9912.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274466,2019-12-02,525.0,95995.0,0.500000,1.0,0.0,2219.0,1664.25,0.0,1.0,173056.0,54.0,54.0,3897.0,NaN
274467,2019-12-02,1034.0,95994.0,1.000000,1.0,0.0,3324.0,1662.00,0.0,1.0,172989.0,203.0,203.0,9912.0,NaN
274468,2019-12-02,764.0,95993.0,0.333333,1.0,0.0,2800.0,1960.00,0.0,0.0,172964.0,219.0,219.0,9912.0,NaN
274469,2019-12-02,1316.0,95996.0,0.937500,1.0,0.0,2478.0,1486.80,4.0,1.0,173348.0,203.0,203.0,3897.0,NaN
274470,2019-12-02,1328.0,96628.0,0.249514,1.0,0.0,5399.0,1619.70,0.0,1.0,175343.0,54.0,54.0,9912.0,NaN

In [ ]:
del train['id_x']

In [ ]:
train.isnull().sum()

period_dt                    0
location_id                  0
product_id                   0
demand                       0
PROMO1_FLAG               1791
PROMO2_FLAG               1791
PRICE_REGULAR             6583
PRICE_AFTER_DISC          8140
NUM_CONSULTANT            1791
AUTORIZATION_FLAG         1791
id                           0
STORE_LOCATION_LVL_RK4       0
STORE_LOCATION_LVL_RK3       0
PRODUCT_LVL_RK6              0
dtype: int64

In [ ]:
train = train.dropna()

In [ ]:
train.isnull().sum()

period_dt                 0
location_id               0
product_id                0
demand                    0
PROMO1_FLAG               0
PROMO2_FLAG               0
PRICE_REGULAR             0
PRICE_AFTER_DISC          0
NUM_CONSULTANT            0
AUTORIZATION_FLAG         0
id                        0
STORE_LOCATION_LVL_RK4    0
STORE_LOCATION_LVL_RK3    0
PRODUCT_LVL_RK6           0
dtype: int64

In [ ]:
train.shape

(266331, 14)

In [ ]:
test.isnull().sum()

period_dt                   0
location_id                 0
product_id                  0
demand                    593
PROMO1_FLAG                 5
PROMO2_FLAG                 5
PRICE_REGULAR              10
PRICE_AFTER_DISC           10
NUM_CONSULTANT              5
AUTORIZATION_FLAG           5
id                        593
STORE_LOCATION_LVL_RK4      0
STORE_LOCATION_LVL_RK3      0
PRODUCT_LVL_RK6             0
id_x                        0
dtype: int64

In [ ]:
test['PROMO1_FLAG'] = test['PROMO1_FLAG'].replace(np.nan, train['PROMO1_FLAG'].median())

In [ ]:
test['PROMO2_FLAG'] = test['PROMO2_FLAG'].replace(np.nan, train['PROMO2_FLAG'].median())
test['PRICE_REGULAR'] = test['PRICE_REGULAR'].replace(np.nan, train['PRICE_REGULAR'].mean())
test['PRICE_AFTER_DISC'] = test['PRICE_AFTER_DISC'].replace(np.nan, train['PRICE_AFTER_DISC'].mean())
test['NUM_CONSULTANT'] = test['NUM_CONSULTANT'].replace(np.nan, train['NUM_CONSULTANT'].mean())
test['AUTORIZATION_FLAG'] = test['AUTORIZATION_FLAG'].replace(np.nan, train['AUTORIZATION_FLAG'].median())

In [ ]:
test.isnull().sum()

period_dt                   0
location_id                 0
product_id                  0
demand                    593
PROMO1_FLAG                 0
PROMO2_FLAG                 0
PRICE_REGULAR               0
PRICE_AFTER_DISC            0
NUM_CONSULTANT              0
AUTORIZATION_FLAG           0
id                        593
STORE_LOCATION_LVL_RK4      0
STORE_LOCATION_LVL_RK3      0
PRODUCT_LVL_RK6             0
id_x                        0
dtype: int64

Начиная отсюда, проблем с пропущенными значениями нет, начинаем попытку повторить HW2 (сем)

In [ ]:
from datetime import date
train['period_dt'] = pd.to_datetime(train['period_dt'])
test['period_dt'] = pd.to_datetime(test['period_dt'])

In [ ]:
train.dtypes

period_dt                 datetime64[ns]
location_id                      float64
product_id                       float64
demand                           float64
PROMO1_FLAG                      float64
PROMO2_FLAG                      float64
PRICE_REGULAR                    float64
PRICE_AFTER_DISC                 float64
NUM_CONSULTANT                   float64
AUTORIZATION_FLAG                float64
id                               float64
STORE_LOCATION_LVL_RK4           float64
STORE_LOCATION_LVL_RK3           float64
PRODUCT_LVL_RK6                  float64
dtype: object

In [ ]:
#Добавим признаки вручную
train = train.reset_index().copy(deep = True)
#train["weekday"] = train.period_dt.dt.weekday
train["monthday"] = train.period_dt.dt.day
#train['is_weekend'] = train.weekday.isin([5,6])*1

test = test.reset_index().copy(deep = True)
#test["weekday"] = test.period_dt.dt.weekday
test["monthday"] = test.period_dt.dt.day
#test['is_weekend'] = test.weekday.isin([5,6])*1

In [ ]:
#Инициализируем функции с семинара
from itertools import product
def percentile(n):
    '''Calculate n - percentile of data'''
    def percentile_(x):
        return np.percentile(x, n)
    percentile_.__name__ = 'pctl%s' % n
    return percentile_

# train[['SKU_id', 'Store_id', 'Demand']].groupby(['SKU_id', 'Store_id']).agg({'mean', 'std', percentile(50)})

# добавляем лаги
def lagged_features(df
                    , target_var = 'demand'
                    , org_id_columns = ['product_rk', 'store_location_rk']
                    , all_id_columns =['product_rk', 'store_location_rk', 'period_start_dt']
                    , lags = [7, 14, 21, 28]
                    , windows = [7, 14]
                    , aggregation_methods = {'mean', 'median', percentile(10),  percentile(90)}
                    , filters = None
                    ):
    '''Calculate lagged features '''
    ''' df - data frame
        target_var - column name which is used to calculate lagged features
        org_id_columns - id columns, lagged featires is calculated within each id element independatnly
        all_id_columns - id columns + timestamp column
        lags -
        windows - list of windows, calculation is performed within time range length of window
        aggregation_methods - method of aggregation, e.g. 'mean', 'median', 'std', etc.
        filter = dict of dict: {<column_name>:{'postfix':'condition of the filter'}}
    '''
    out_df = deepcopy(df)

    if filters is None:
      filters = {'':{''}}

    keys, values = zip(*filters.items())
    for bundle in product(*values):
      # print(bundle)
        # define dates for each SKU and Store pairs
      condition = ' & '.join([keys[i]+ filters[keys[i]][bundle[i]] for i in range(len(keys))])
      name =  '_'.join([bundle[i] for i in range(len(keys))])
      if len(condition) >0:
        _idx = df.eval(condition)
      else:
        _idx = df.index>=0

      if len(df[_idx].index)>0:
        for w in windows:
          lf_df = df[_idx].set_index(all_id_columns)[target_var].\
                    groupby(level=org_id_columns).apply(lambda x: x.rolling(window=w, min_periods = 1).agg(aggregation_methods))
          for l in lags:
            new_names = {x: "lag{0}_wdw{1}_{2}_{3}".
                          format(l, w, x, name) for x in lf_df.columns }

            out_df = pd.merge(out_df, lf_df.shift(l).reset_index().rename(columns = new_names),
                  how='left', on =all_id_columns )


    return out_df

In [ ]:
from ipywidgets import IntProgress

from itertools import product
def percentile(n):
    '''Calculate n - percentile of data'''
    def percentile_(x):
        return np.percentile(x, n)
    percentile_.__name__ = 'pctl%s' % n
    return percentile_

# add missing dates to GroupBy.Core object
def fill_missing_dates(x, date_col):
    min_date, max_date = x[date_col].min(), x[date_col].max()
    groupby_day = x.groupby(pd.PeriodIndex(x[date_col], freq='D'))
    results = groupby_day.sum(min_count=1)

    idx = pd.period_range(min_date, max_date)
    results = results.reindex(idx, fill_value=np.nan)

    results.index.rename(date_col, inplace=True)

    return results


def calc_preag_fill(data, group_col, date_col, target_cols, preagg_method):
    ## calc preaggregation
    data_preag = data.groupby(group_col).agg(
        preagg_method)[target_cols].reset_index()

    ## fill missing dates
    data_preag_filled = data_preag.groupby(group_col[:-1]).apply(
        fill_missing_dates, date_col=date_col).drop(group_col[:-1],
                                                    axis=1).reset_index()

    ## return DataFrame with calculated preaggregation and filled missing dates
    return data_preag_filled


def calc_rolling(data_preag_filled, group_col, date_col, method, w):

    ## calc rolling stats
    lf_df_filled = data_preag_filled.groupby(group_col[:-1]).\
        apply(lambda x: x.set_index(date_col).rolling(window=w, min_periods=1).agg(method)).drop(group_col[:-1], axis=1)

    ## return DataFrame with rolled columns from target_vars
    return lf_df_filled


def calc_ewm(data_preag_filled, group_col, date_col, span):
    ## calc ewm stats
    lf_df_filled = data_preag_filled.groupby(group_col[:-1]).\
        apply(lambda x: x.set_index(date_col).ewm(span=span).mean()).drop(group_col[:-1], axis=1)

    ## return DataFrame with rolled columns from target_vars
    return lf_df_filled


def shift(lf_df_filled, group_col, date_col, lag):

    lf_df = lf_df_filled.groupby(
        level=group_col[:-1]).apply(lambda x: x.shift(lag)).reset_index()
    lf_df[date_col] = pd.to_datetime(lf_df[date_col].astype(str))

    ## return DataFrame with following columns: filter_col, id_cols, date_col and shifted stats
    return lf_df


def generate_lagged_features(
        data: pd.DataFrame,
        target_cols: list = ['Demand'],
        id_cols: list = ['SKU_id', 'Store_id'],
        date_col: str = 'Date',
        lags: list = [7, 14, 21, 28],
        windows: list = ['7D', '14D', '28D', '56D'],
        preagg_methods: list = ['mean'],
        agg_methods: list = ['mean', 'median', percentile(10), pd.Series.skew],
        dynamic_filters: list = ['weekday', 'Promo'],
        ewm_params: dict = {'weekday': [14, 28], 'Promo': [14, 42]}) -> pd.DataFrame:

    '''
    data - dataframe with default index
    target_cols - column names for lags calculation
    id_cols - key columns to identify unique values
    date_col - column with datetime format values
    lags - lag values(days)
    windows - windows(days/weeks/months/etc.),
        calculation is performed within time range length of window
    preagg_methods - applied methods before rolling to make
        every value unique for given id_cols
    agg_methods - method of aggregation('mean', 'median', percentile, etc.)
    dynamic_filters - column names to use as filter
    ewm_params - span values(days) for each dynamic_filter
    '''

    data = data.sort_values(date_col)
    out_df = deepcopy(data)
    dates = [min(data[date_col]), max(data[date_col])]

    total = len(target_cols) * len(lags) * len(windows) * len(preagg_methods) * len(agg_methods) * len(dynamic_filters)
    progress = IntProgress(min=0, max=total)
    display(progress)

    for filter_col in dynamic_filters:
        group_col = [filter_col] + id_cols + [date_col]
        for lag in lags:
            for preagg in preagg_methods:
                data_preag_filled = calc_preag_fill(data, group_col, date_col,
                                                    target_cols, preagg)

                ## add ewm features
                for alpha in ewm_params.get(filter_col, []):
                    ewm_filled = calc_ewm(data_preag_filled, group_col,
                                          date_col, alpha)
                    ewm = shift(ewm_filled, group_col, date_col, lag)
                    new_names = {x: "{0}_lag{1}d_alpha{2}_key{3}_preag{4}_{5}_dynamic_ewm".\
                        format(x, lag, alpha, '_'.join(id_cols), preagg, filter_col) for x in target_cols}

                    out_df = pd.merge(out_df,
                                      ewm.rename(columns=new_names),
                                      how='left',
                                      on=group_col)

                ## add rolling features
                for w in windows:
                    for method in agg_methods:
                        rolling_filled = calc_rolling(data_preag_filled,
                                                      group_col, date_col,
                                                      method, w)

                        ## lf_df - DataFrame with following columns: filter_col, id_cols, date_col, shifted rolling stats
                        rolling = shift(rolling_filled, group_col, date_col,
                                        lag)

                        method_name = method.__name__ if type(
                            method) != str else method

                        new_names = {x: "{0}_lag{1}d_w{2}_key{3}_preag{4}_ag{5}_{6}_dynamic_rolling".\
                                     format(x, lag, w, '_'.join(id_cols), preagg, method_name, filter_col) for x in target_cols}

                        out_df = pd.merge(out_df,
                                          rolling.rename(columns=new_names),
                                          how='left',
                                          on=group_col)
                        progress.value += 1

    return out_df

In [ ]:
from time import time

In [ ]:
%%time
target_cols = ['demand']
id_cols = ['id']
date_col = 'period_dt'
built_in_funcs = [pd.Series.kurtosis, pd.Series.skew]

train['NoFilter'] = 1
train_lagged = generate_lagged_features(train
                    , target_cols = target_cols
                    , id_cols = id_cols
                    , date_col = date_col
                    , lags = [28, 35, 40]
                    , windows = ['14D', '21D', '28D', '56D']
                    , preagg_methods = ['sum'] # ['mean', 'count']
                    , agg_methods = ['mean', 'count', percentile(25),  percentile(75)]
                    , dynamic_filters = ['PROMO1_FLAG', 'NoFilter']
                    , ewm_params={'NoFilter': [14, 28], 'PROMO1_FLAG': [14, 28]}
                    )

test['NoFilter'] = 1
test_lagged = generate_lagged_features(test
                    , target_cols = target_cols
                    , id_cols = id_cols
                    , date_col = date_col
                    , lags = [28, 35, 40]
                    , windows = ['14D', '21D', '28D', '56D']
                    , preagg_methods = ['sum'] # ['mean', 'count']
                    , agg_methods = ['mean', 'min', 'count', percentile(25),  percentile(75)]
                    , dynamic_filters = ['PROMO1_FLAG', 'NoFilter']
                    , ewm_params={'NoFilter': [14, 28], 'PROMO1_FLAG': [14, 28]}
                    )

IntProgress(value=0, max=72)

AttributeError: ignored